name: todo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^6.2.0
  flutter_adaptive_scaffold: ^0.1.7+2
  uuid: ^3.0.7
  either_dart: ^0.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  shimmer_animation: ^2.1.0+1
  json_annotation: ^4.8.1
  hive: ^2.2.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  firebase_core: ^2.26.0
  firebase_auth: ^4.17.7
  firebase_ui_auth: ^1.13.1
  cloud_firestore: ^4.15.8
  meta: ^1.10.0
  firebase_crashlytics: ^3.4.18
  path_provider: ^2.1.0
  fl_chart: ^0.66.2
  context_menus: ^1.0.2
  universal_html: ^2.2.4
  firebase_messaging: ^14.7.19
  googleapis_auth: ^1.6.0
  dio: ^5.4.3+1
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  build_runner: ^2.4.1
  flutter_lints: ^2.0.1

flutter:


  uses-material-design: true
  assets:
    - images/launch_icon.png
#  assets:
#    - lib/application/core/todo-app-firebase-adminsdk.json
#   To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launch_icon"
  ios: true
  image_path: "images/launch_icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "images/launch_icon.png"